import PDFDocument from "pdfkit";

import type { ReportColumn, ReportDocument } from "@/features/reports/types";

const PAGE_MARGIN = 36;
const HEADER_HEIGHT = 22;
const ROW_HEIGHT = 22;

type PdfDocument = InstanceType<typeof PDFDocument>;

function cellText(value: unknown): string {
  if (value === null || value === undefined || value === "") return "-";
  return String(value);
}

function truncate(value: string, maxChars: number): string {
  if (value.length <= maxChars) return value;
  return `${value.slice(0, Math.max(0, maxChars - 1))}...`;
}

function writeFooter(doc: PdfDocument): void {
  const page = doc.bufferedPageRange().count;
  doc
    .fontSize(8)
    .fillColor("#6b7280")
    .text(
      `Generated by CSU PRIME-HR | Page ${page}`,
      PAGE_MARGIN,
      doc.page.height - PAGE_MARGIN + 12,
      {
        align: "center",
        width: doc.page.width - PAGE_MARGIN * 2,
      },
    );
}

function ensureSpace(doc: PdfDocument, neededHeight: number): void {
  if (doc.y + neededHeight <= doc.page.height - PAGE_MARGIN) return;
  writeFooter(doc);
  doc.addPage();
}

function writeKeyValue(doc: PdfDocument, label: string, value: string): void {
  doc
    .font("Helvetica-Bold")
    .fillColor("#111827")
    .text(`${label}: `, { continued: true });
  doc.font("Helvetica").fillColor("#374151").text(value);
}

function columnWidths(
  columns: ReportColumn[],
  availableWidth: number,
): number[] {
  const declaredWidth = columns.reduce(
    (total, column) => total + (column.width ?? 18),
    0,
  );
  return columns.map(
    (column) => ((column.width ?? 18) / declaredWidth) * availableWidth,
  );
}

function writeTable(
  doc: PdfDocument,
  columns: ReportColumn[],
  rows: Array<Record<string, unknown>>,
): void {
  const availableWidth = doc.page.width - PAGE_MARGIN * 2;
  const widths = columnWidths(columns, availableWidth);

  ensureSpace(doc, HEADER_HEIGHT + ROW_HEIGHT);
  let x = PAGE_MARGIN;
  const headerY = doc.y;
  doc.rect(PAGE_MARGIN, headerY, availableWidth, HEADER_HEIGHT).fill("#374151");
  columns.forEach((column, index) => {
    doc
      .fillColor("#ffffff")
      .font("Helvetica-Bold")
      .fontSize(7)
      .text(
        truncate(column.header, Math.max(7, Math.floor(widths[index] / 4))),
        x + 4,
        headerY + 7,
        {
          width: widths[index] - 8,
          lineBreak: false,
        },
      );
    x += widths[index];
  });
  doc.y = headerY + HEADER_HEIGHT;

  rows.forEach((row, rowIndex) => {
    ensureSpace(doc, ROW_HEIGHT);
    const rowY = doc.y;
    doc
      .rect(PAGE_MARGIN, rowY, availableWidth, ROW_HEIGHT)
      .fill(rowIndex % 2 === 0 ? "#ffffff" : "#f9fafb");
    x = PAGE_MARGIN;
    columns.forEach((column, index) => {
      doc
        .fillColor("#111827")
        .font("Helvetica")
        .fontSize(7)
        .text(
          truncate(
            cellText(row[column.key]),
            Math.max(8, Math.floor(widths[index] / 4)),
          ),
          x + 4,
          rowY + 7,
          { width: widths[index] - 8, lineBreak: false },
        );
      x += widths[index];
    });
    doc.y = rowY + ROW_HEIGHT;
  });
}

export async function generateReportPdf(
  report: ReportDocument,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      layout: "landscape",
      margin: PAGE_MARGIN,
      bufferPages: true,
      info: {
        Title: report.definition.title,
        Author: "CSU PRIME-HR",
        Subject: report.definition.description,
      },
    });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .fillColor("#111827")
      .text(report.definition.title);
    doc.moveDown(0.25);
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#4b5563")
      .text(report.definition.description);
    doc.moveDown(0.75);

    writeKeyValue(
      doc,
      "Generated",
      new Date(report.generatedAt).toLocaleString(),
    );
    writeKeyValue(doc, "Scope", report.scopeLabel);
    writeKeyValue(
      doc,
      "Filters",
      `campus=${report.filters.campusId ?? "all authorized"}; office=${report.filters.officeId ?? "all authorized"}; from=${report.filters.from ?? "none"}; to=${report.filters.to ?? "none"}`,
    );
    doc.moveDown(0.75);

    if (report.summary.length > 0) {
      doc
        .font("Helvetica-Bold")
        .fontSize(11)
        .fillColor("#111827")
        .text("Summary");
      doc.moveDown(0.25);
      report.summary.forEach((item) =>
        writeKeyValue(doc, item.label, String(item.value)),
      );
      doc.moveDown(0.75);
    }

    report.datasets.forEach((dataset, index) => {
      if (index > 0) {
        ensureSpace(doc, 80);
      }
      doc
        .font("Helvetica-Bold")
        .fontSize(12)
        .fillColor("#111827")
        .text(dataset.title);
      if (dataset.description) {
        doc
          .font("Helvetica")
          .fontSize(8)
          .fillColor("#4b5563")
          .text(dataset.description);
      }
      doc.moveDown(0.35);
      writeTable(doc, dataset.columns, dataset.rows);
      doc.moveDown(0.8);
    });

    writeFooter(doc);
    doc.end();
  });
}
